name: deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn

      - name: Update caniuse-lite.
        run: npx browserslist@latest --update-db

      - name: Enable legacy OpenSSL provider
        run: export NODE_OPTIONS=--openssl-legacy-provider

      - name: Build application
        run: yarn build

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install Surge
        run: npm install -g surge

      - name: Install dependencies
        run: yarn

      - name: Update caniuse-lite.
        run: npx browserslist@latest --update-db

      - name: Enable legacy OpenSSL provider
        run: export NODE_OPTIONS=--openssl-legacy-provider

      - name: Build application
        run: yarn build

      - name: Export application
        run: yarn export

      - name: Deploy application
        run: surge out mcgill.hack4impact.org --token ${{secrets.SURGE_TOKEN}}
